//[sqlcode.txt file time=2013/11/20 12:22:35]
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is generated by the sql header file tool sqlgen.exe. Please do 
// not modify this file directly. Change the sqlcode.txt file instead.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 


#ifndef __PROJECT_SQL_STRING_H__          
#define __PROJECT_SQL_STRING_H__           



#if defined(_UNICODE) || defined(UNICODE)       
typedef wchar_t  CharT;	    
#else					 
typedef char     CharT;		
#endif						




struct st_sql_data	
{
	const CharT*    pSQLID;
	const CharT*    pCommonSQL;
	const CharT*    pOracleSQL;
	const CharT*    pMySQLSQL;
	const CharT*    pSQLiteSQL;
};



static const st_sql_data  s_SQLArray[]=	
{   


//[0][SYS_SYSDATE_NOW]

//[0][SYS_SYSDATE_NOW]
	{
		/*SQLID*/("SYS_SYSDATE_NOW_SELECT_1000"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(SYSDATE'YYYY-MM-DD HH24:MI:SS') AS SYSDATENOW  FROM DUAL"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(SYSDATE(),'%%Y-%%m-%%d %%H:%%i:%%S') AS SYSDATENOW FROM DUAL"),
		/*SQLiteSQL*/("SELECT STRFTIME('%%Y-%%m-%%d %%H:%%M:%%S', 'now', 'localtime') AS SYSDATENOW")	
	},
	{
		/*SQLID*/("SYS_SYSDATE_NOW_SELECT_1001"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') AS SYSDATENOW FROM DUAL"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(SYSDATE(),'%%Y%%m%%d%%H%%i%%S') AS SYSDATENOW FROM DUAL"),
		/*SQLiteSQL*/("SELECT STRFTIME('%%Y%%m%%d%%H%%M%%S', 'now', 'localtime') AS SYSDATENOW")	
	},
	{
		/*SQLID*/("SYS_SYSDATE_NOW_SELECT_1002"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS.FF3') AS SYSDATENOW FROM DUAL"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(CURRENT_TIMESTAMP(),'%%Y-%%m-%%d %%H:%%i:%%S.%%f') AS SYSDATENOW FROM DUAL"),
		/*SQLiteSQL*/("SELECT STRFTIME('%%Y-%%m-%%d %%H:%%M.%%f', 'now', 'localtime') AS SYSDATENOW")	
	},
	{
		/*SQLID*/("SYS_SYSDATE_NOW_SELECT_1003"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3') AS SYSDATENOW FROM DUAL"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(CURRENT_TIMESTAMP(),'%%Y%%m%%d%%H%%i%%S%%f') AS SYSDATENOW FROM DUAL"),
		/*SQLiteSQL*/("SELECT STRFTIME('%%Y%%m%%d%%H%%M%%f', 'now', 'localtime') AS SYSDATENOW")	
	},

//[1][TABLE_TEST_DAITEST]
	{
		/*SQLID*/("TABLETESTDAITEST_SELECT_1000"),
		/*CommonSQL*/("SELECT STR_COLUMN FROM TABLE_TEST_DAITEST WHERE LINE_ID = 1000"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},
	{
		/*SQLID*/("TABLETESTDAITEST_SELECT_1001"),
		/*CommonSQL*/("SELECT LINE_ID, TEST_TYPE, INT_COLUMN, STR_COLUMN, BOOL_COLUMN, REAL_COLUMN, DATE_COLUMN, TIMESTAMP_COLUMN FROM TABLE_TEST_DAITEST WHERE LINE_ID = 1000"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},
	{
		/*SQLID*/("TABLETESTDAITEST_UPDATE_3000"),
		/*CommonSQL*/("UPDATE TABLE_TEST_DAITEST SET INT_COLUMN=5000, STR_COLUMN='SQL_UPDATE_OK' WHERE LINE_ID = 1000"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},
	{
		/*SQLID*/("TABLETESTDAITEST_DELETE_4000"),
		/*CommonSQL*/("DELETE FROM TABLE_TEST_DAITEST WHERE LINE_ID = 1000"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},
	{
		/*SQLID*/("TABLETESTDAITEST_DROP_5000"),
		/*CommonSQL*/("DROP TABLE TABLE_TEST_DAITEST"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},

//[1][TABLE_TEST_DAITEST]
	{
		/*SQLID*/("TABLETESTDAITEST_INSERT_2000"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("INSERT INTO TABLE_TEST_DAITEST(LINE_ID, TEST_TYPE, INT_COLUMN, STR_COLUMN, BOOL_COLUMN, REAL_COLUMN,\
 DATE_COLUMN, TIMESTAMP_COLUMN) VALUES (1000, 'Test_Type_NormalValue', 1000000, 'str_normal_value', 1, 10000000.10001, TO_DATE('%s','dd/mm/yyyy hh24:mi:ss'), TO_DATE('%s','dd/mm/yyyy hh24:mi:ss'))"),
		/*MySQLSQL*/("INSERT INTO TABLE_TEST_DAITEST(LINE_ID, TEST_TYPE, INT_COLUMN, STR_COLUMN, BOOL_COLUMN, REAL_COLUMN,\
 DATE_COLUMN, TIMESTAMP_COLUMN) VALUES (1000, 'Test_Type_NormalValue', 1000000, 'str_normal_value', 1, 10000000.10001, '%s', '%s')"),
		/*SQLiteSQL*/("INSERT INTO TABLE_TEST_DAITEST(LINE_ID, TEST_TYPE, INT_COLUMN, STR_COLUMN, BOOL_COLUMN, REAL_COLUMN,\
 DATE_COLUMN, TIMESTAMP_COLUMN) VALUES (1000, 'Test_Type_NormalValue', 1000000, 'str_normal_value', 1, 10000000.10001, '%s', '%s')")	
	},
	{
		/*SQLID*/("TABLETESTDAITEST_CREATE_6000"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("CREATE TABLE TABLE_TEST_DAITEST(LINE_ID NUMBER, TEST_TYPE VARCHAR2(200), INT_COLUMN NUMBER, STR_COLUMN VARCHAR2(200), BOOL_COLUMN NUMBER, REAL_COLUMN NUMBER(20,8),\
 DATE_COLUMN DATE, TIMESTAMP_COLUMN TIMESTAMP)"),
		/*MySQLSQL*/("CREATE TABLE TABLE_TEST_DAITEST(LINE_ID int, TEST_TYPE VARCHAR(200), INT_COLUMN int, STR_COLUMN VARCHAR(200), BOOL_COLUMN int, REAL_COLUMN double,\
 DATE_COLUMN DATETIME, TIMESTAMP_COLUMN TIMESTAMP)"),
		/*SQLiteSQL*/("CREATE TABLE TABLE_TEST_DAITEST(LINE_ID NUMBER, TEST_TYPE VARCHAR(200), INT_COLUMN NUMBER, STR_COLUMN VARCHAR(200), BOOL_COLUMN NUMBER, REAL_COLUMN NUMBER(20,8),\
 DATE_COLUMN TIMESTAMP, TIMESTAMP_COLUMN TIMESTAMP)")	
	},


}; //static const st_sql_data  s_SQLArray[]  


 #endif//__PROJECT_SQL_STRING_H__           

