//[sqlcode.txt file time=2013/11/16 12:35:56]
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is generated by the sql header file tool sqlgen.exe. Please do 
// not modify this file directly. Change the sqlcode.txt file instead.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 


#ifndef SQL_H          
#define SQL_H           



#if defined(_UNICODE) || defined(UNICODE)       
typedef wchar_t  CharT;	    
#else					 
typedef char     CharT;		
#endif						




struct st_sql_data	
{
	const CharT*    pSQLID;
	const CharT*    pCommonSQL;
	const CharT*    pOracleSQL;
	const CharT*    pMySQLSQL;
	const CharT*    pSQLiteSQL;
};



static const st_sql_data  s_SQLArray[]=	
{   


//[0][AlarmRule]
	{
		/*SQLID*/("ALARMRULE_SELECT_1001"),
		/*CommonSQL*/("SELECT pkey, ruleType FROM alarmrule"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},

//[0][AlarmRule]
	{
		/*SQLID*/("ALARMRULE_SELECT_1052"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(DATE_CREATED,'YYYYMMDDHH24MISS') from alarmrule where pkey = %s"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(DATE_CREATED,'%%Y%%m%%d%%H%%i%%S') from alarmrule where pkey = %s"),
		/*SQLiteSQL*/("SELECT TO_CHAR(DATE_CREATED,'YYYYMMDDHH24MISS') from alarmrule where pkey = %s")	
	},

//[1][AlarmRuleType]
	{
		/*SQLID*/("ALARMRULETYPE_SELECT_1001"),
		/*CommonSQL*/("SELECT pkey, ruleType FROM alarmruletype"),
		/*OracleSQL*/(""),
		/*MySQLSQL*/(""),
		/*SQLiteSQL*/("")	
	},

//[1][AlarmRuleType]
	{
		/*SQLID*/("ALARMRULETYPE_SELECT_1052"),
		/*CommonSQL*/(""),
		/*OracleSQL*/("SELECT TO_CHAR(DATE_CREATED,'YYYYMMDDHH24MISS') from alarmruletype where pkey = %s"),
		/*MySQLSQL*/("SELECT DATE_FORMAT(DATE_CREATED,'%%Y%%m%%d%%H%%i%%S') from alarmruletype where pkey = %s"),
		/*SQLiteSQL*/("SELECT TO_CHAR(DATE_CREATED,'YYYYMMDDHH24MISS') from alarmruletype where pkey = %s")	
	},


}; //static const st_sql_data  s_SQLArray[]  


 #endif//SQL_H           

