//[sqlcode.txt file time=2013/11/16 17:07:36]
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is generated by the sql header file tool sqlgen.exe. Please do 
// not modify this file directly. Change the sqlcode.txt file instead.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 


#ifndef SQLMACRODEF_H          
#define SQLMACRODEF_H           


//[0][TABLE_TEST_DAITEST]
//[[common]]
#define 	TABLETESTDAITEST_SELECT_1000 	 "TABLETESTDAITEST_SELECT_1000"
#define 	TABLETESTDAITEST_UPDATE_3000 	 "TABLETESTDAITEST_UPDATE_3000"
#define 	TABLETESTDAITEST_DELETE_4000 	 "TABLETESTDAITEST_DELETE_4000"
#define 	TABLETESTDAITEST_DROP_5000 	 "TABLETESTDAITEST_DROP_5000"

//[0][TABLE_TEST_DAITEST]
//[[oracle]][[mysql]]
#define 	TABLETESTDAITEST_INSERT_2000 	 "TABLETESTDAITEST_INSERT_2000"
#define 	TABLETESTDAITEST_CREATE_6000 	 "TABLETESTDAITEST_CREATE_6000"

//[1][AlarmRule]
//[[common]]
#define 	ALARMRULE_SELECT_1001 	 "ALARMRULE_SELECT_1001"

//[1][AlarmRule]
//[[oracle]][[mysql]]
#define 	ALARMRULE_SELECT_1002 	 "ALARMRULE_SELECT_1002"

//[2][AlarmRuleType]
//[[common]]
#define 	ALARMRULETYPE_SELECT_1001 	 "ALARMRULETYPE_SELECT_1001"

//[2][AlarmRuleType]
//[[oracle]][[mysql]]
#define 	ALARMRULETYPE_SELECT_1002 	 "ALARMRULETYPE_SELECT_1002"


#endif//SQLMACRODEF_H           

