# The source code in this file is the property of
# Ripple Systems and is not for redistribution
# in any form.
#
# $File: //depot/3001_TIP_NEW/TA_BASE/transactive/core/versioning/Makefile $
# $Revision: #2 $
# $DateTime: 2012/02/06 16:15:14 $
# $Author: haijun.li $
#
# This file builds the TA_Version library.
#

PROJ_ROOT_DIR	= ../../../..
PROJ_CODE_DIR	= transactive/core/versioning
PROJ_NAME	= TA_Version
PROJ_SOURCE	= Version.cpp 
PROJ_TYPE	= lib
PROJ_INC_DIR	= ./src
PROJ_OUT_DIR	= $(PROJ_ROOT_DIR)/sdk/$(OPERATING_SYSTEM)_$(STRING_FLAG)$(RELEASE_FLAG)

##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################
include $(PROJ_ROOT_DIR)/code/tools/build/CommonMakefile.mak

install:
	# Do Nothing

